#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "$0")/.." && pwd)"
WORKER_DIR="$ROOT_DIR/webjs-approval-worker"
LOG_DIR="$ROOT_DIR/logs"
LOG_FILE="$LOG_DIR/registration_group_webjs_worker.log"
mkdir -p "$LOG_DIR"

: "${REGISTRATION_GROUP_APPROVAL_WEBJS_AUTH_MODE:=chrome_profile_copy}"
: "${REGISTRATION_GROUP_APPROVAL_WEBJS_AUTH_DATA_PATH:=$WORKER_DIR/.wwebjs_auth_dedicated}"
: "${REGISTRATION_GROUP_APPROVAL_WEBJS_CLIENT_ID:=registration-group-approval}"
: "${REGISTRATION_GROUP_APPROVAL_WEBJS_CHROME_USER_DATA_ROOT:=$HOME/Library/Application Support/Google/Chrome}"
: "${REGISTRATION_GROUP_APPROVAL_WEBJS_CHROME_PROFILE_DIR:=Profile 25}"
: "${REGISTRATION_GROUP_APPROVAL_WEBJS_APPROVE_CALL_TIMEOUT_MS:=15000}"
: "${REGISTRATION_GROUP_APPROVAL_WEBJS_PER_REQUESTER_TIMEOUT_MS:=5000}"
: "${REGISTRATION_GROUP_APPROVAL_WEBJS_PER_REQUESTER_SLEEP_MS:=50}"
: "${REGISTRATION_GROUP_APPROVAL_WEBJS_VERIFY_WAIT_MS:=1200}"
: "${REGISTRATION_GROUP_APPROVAL_WEBJS_VERIFY_RETRIES:=4}"

if [[ "$REGISTRATION_GROUP_APPROVAL_WEBJS_AUTH_MODE" != "chrome_profile_copy" && "$REGISTRATION_GROUP_APPROVAL_WEBJS_AUTH_MODE" != "dedicated_localauth" ]]; then
  echo "unsupported auth mode: $REGISTRATION_GROUP_APPROVAL_WEBJS_AUTH_MODE" >&2
  exit 2
fi

if [[ "$REGISTRATION_GROUP_APPROVAL_WEBJS_AUTH_MODE" == "chrome_profile_copy" ]]; then
  if [[ ! -d "$REGISTRATION_GROUP_APPROVAL_WEBJS_CHROME_USER_DATA_ROOT/$REGISTRATION_GROUP_APPROVAL_WEBJS_CHROME_PROFILE_DIR" ]]; then
    echo "missing chrome profile: $REGISTRATION_GROUP_APPROVAL_WEBJS_CHROME_USER_DATA_ROOT/$REGISTRATION_GROUP_APPROVAL_WEBJS_CHROME_PROFILE_DIR" >&2
    exit 2
  fi
fi

if lsof -ti tcp:8787 >/dev/null 2>&1; then
  lsof -ti tcp:8787 | xargs kill || true
  sleep 1
fi

cd "$WORKER_DIR"
if [[ "$REGISTRATION_GROUP_APPROVAL_WEBJS_AUTH_MODE" == "chrome_profile_copy" ]]; then
  nohup env \
    REGISTRATION_GROUP_APPROVAL_WEBJS_AUTH_MODE="$REGISTRATION_GROUP_APPROVAL_WEBJS_AUTH_MODE" \
    REGISTRATION_GROUP_APPROVAL_WEBJS_CLIENT_ID="$REGISTRATION_GROUP_APPROVAL_WEBJS_CLIENT_ID" \
    REGISTRATION_GROUP_APPROVAL_WEBJS_AUTH_DATA_PATH="$REGISTRATION_GROUP_APPROVAL_WEBJS_AUTH_DATA_PATH" \
    REGISTRATION_GROUP_APPROVAL_WEBJS_CHROME_USER_DATA_ROOT="$REGISTRATION_GROUP_APPROVAL_WEBJS_CHROME_USER_DATA_ROOT" \
    REGISTRATION_GROUP_APPROVAL_WEBJS_CHROME_PROFILE_DIR="$REGISTRATION_GROUP_APPROVAL_WEBJS_CHROME_PROFILE_DIR" \
    REGISTRATION_GROUP_APPROVAL_WEBJS_APPROVE_CALL_TIMEOUT_MS="$REGISTRATION_GROUP_APPROVAL_WEBJS_APPROVE_CALL_TIMEOUT_MS" \
    REGISTRATION_GROUP_APPROVAL_WEBJS_PER_REQUESTER_TIMEOUT_MS="$REGISTRATION_GROUP_APPROVAL_WEBJS_PER_REQUESTER_TIMEOUT_MS" \
    REGISTRATION_GROUP_APPROVAL_WEBJS_PER_REQUESTER_SLEEP_MS="$REGISTRATION_GROUP_APPROVAL_WEBJS_PER_REQUESTER_SLEEP_MS" \
    REGISTRATION_GROUP_APPROVAL_WEBJS_VERIFY_WAIT_MS="$REGISTRATION_GROUP_APPROVAL_WEBJS_VERIFY_WAIT_MS" \
    REGISTRATION_GROUP_APPROVAL_WEBJS_VERIFY_RETRIES="$REGISTRATION_GROUP_APPROVAL_WEBJS_VERIFY_RETRIES" \
    npm start >> "$LOG_FILE" 2>&1 &
else
  nohup env \
    REGISTRATION_GROUP_APPROVAL_WEBJS_AUTH_MODE="$REGISTRATION_GROUP_APPROVAL_WEBJS_AUTH_MODE" \
    REGISTRATION_GROUP_APPROVAL_WEBJS_CLIENT_ID="$REGISTRATION_GROUP_APPROVAL_WEBJS_CLIENT_ID" \
    REGISTRATION_GROUP_APPROVAL_WEBJS_AUTH_DATA_PATH="$REGISTRATION_GROUP_APPROVAL_WEBJS_AUTH_DATA_PATH" \
    REGISTRATION_GROUP_APPROVAL_WEBJS_APPROVE_CALL_TIMEOUT_MS="$REGISTRATION_GROUP_APPROVAL_WEBJS_APPROVE_CALL_TIMEOUT_MS" \
    REGISTRATION_GROUP_APPROVAL_WEBJS_PER_REQUESTER_TIMEOUT_MS="$REGISTRATION_GROUP_APPROVAL_WEBJS_PER_REQUESTER_TIMEOUT_MS" \
    REGISTRATION_GROUP_APPROVAL_WEBJS_PER_REQUESTER_SLEEP_MS="$REGISTRATION_GROUP_APPROVAL_WEBJS_PER_REQUESTER_SLEEP_MS" \
    REGISTRATION_GROUP_APPROVAL_WEBJS_VERIFY_WAIT_MS="$REGISTRATION_GROUP_APPROVAL_WEBJS_VERIFY_WAIT_MS" \
    REGISTRATION_GROUP_APPROVAL_WEBJS_VERIFY_RETRIES="$REGISTRATION_GROUP_APPROVAL_WEBJS_VERIFY_RETRIES" \
    npm start >> "$LOG_FILE" 2>&1 &
fi

for _ in {1..15}; do
  sleep 2
  if curl -sf -X POST http://127.0.0.1:8787/warmup >/dev/null 2>&1; then
    curl -s http://127.0.0.1:8787/health
    exit 0
  fi
done

echo "worker restart timed out; check $LOG_FILE" >&2
exit 1
